import os
import json
from urllib.parse import urlparse
from firecrawl import FirecrawlApp
from dotenv import load_dotenv

load_dotenv()

# Initialize Firecrawl App
fire_crawl_api_key=os.getenv("FIRE_CRAWL_API_KEY")
app = FirecrawlApp(api_key=fire_crawl_api_key)

# List of Angular documentation URLs to scrape
urls= [
#'https://angular.dev/guide/signals',
    #'https://angular.dev/guide/signals/linked-signal',
    #'https://angular.dev/guide/signals/resource',
    #'https://angular.dev/guide/components',
    #'https://angular.dev/guide/components/selectors',
    #'https://angular.dev/guide/components/styling',
    #'https://angular.dev/guide/components/inputs',
    #'https://angular.dev/guide/components/outputs',
    #'https://angular.dev/guide/components/content-projection',
    #'https://angular.dev/guide/components/host-elements',
    #'https://angular.dev/guide/components/lifecycle',
    #'https://angular.dev/guide/components/queries',
    #'https://angular.dev/guide/components/dom-apis',
    #'https://angular.dev/guide/components/inheritance',
    #'https://angular.dev/guide/components/programmatic-rendering',
    
    #'https://angular.dev/guide/components/advanced-configuration',
    #'https://angular.dev/guide/templates',
    #'https://angular.dev/guide/templates/binding',
    #'https://angular.dev/guide/templates/event-listeners',
    #'https://angular.dev/guide/templates/two-way-binding',
    #'https://angular.dev/guide/templates/control-flow',
    #'https://angular.dev/guide/templates/pipes',
    #'https://angular.dev/guide/templates/ng-content',
    #'https://angular.dev/guide/templates/ng-template',
    #'https://angular.dev/guide/templates/ng-container',
    #'https://angular.dev/guide/templates/variables',
    #'https://angular.dev/guide/templates/defer',
    
    #'https://angular.dev/guide/templates/expression-syntax',
    #'https://angular.dev/guide/templates/whitespace',
    #'https://angular.dev/guide/directivess',
    #'https://angular.dev/guide/directives/attribute-directives',
    #'https://angular.dev/guide/directives/structural-directives',
    #'https://angular.dev/guide/directives/directive-composition-api',
    #'https://angular.dev/guide/image-optimization',
    #'https://angular.dev/guide/di',
    #'https://angular.dev/guide/di/dependency-injection',
    #'https://angular.dev/guide/di/creating-injectable-service',
    #'https://angular.dev/guide/di/dependency-injection-providers',
    #'https://angular.dev/guide/di/dependency-injection-context',
    #'https://angular.dev/guide/di/hierarchical-dependency-injection',
    #'https://angular.dev/guide/di/lightweight-injection-tokens',
    #'https://angular.dev/guide/di/di-in-action',
    #'https://angular.dev/guide/routing',
    #'https://angular.dev/guide/routing/common-router-tasks',
    #'https://angular.dev/guide/routing/router-tutorial',
    #'https://angular.dev/guide/routing/routing-with-urlmatcher',
    #'https://angular.dev/guide/routing/router-reference',
    #'https://angular.dev/guide/forms',
    #'https://angular.dev/guide/forms/reactive-forms',
    #'https://angular.dev/guide/forms/typed-forms',
    #'https://angular.dev/guide/forms/template-driven-forms',
    #'https://angular.dev/guide/forms/form-validation',
    #'https://angular.dev/guide/forms/dynamic-forms',
    #'https://angular.dev/guide/http',
    #'https://angular.dev/guide/http/setup',
    #'https://angular.dev/guide/http/making-requests',
    #'https://angular.dev/guide/http/interceptors',
    #'https://angular.dev/guide/http/testing',
    #'https://angular.dev/guide/performance',
    #'https://angular.dev/guide/ssr',
    #'https://angular.dev/guide/prerendering',
    
    #'https://angular.dev/guide/hybrid-rendering',
    #'https://angular.dev/guide/hydration',
    #'https://angular.dev/guide/incremental-hydration',
    #'https://angular.dev/guide/testing',
    #'https://angular.dev/guide/testing/code-coverage',
    #'https://angular.dev/guide/testing/services',
    #'https://angular.dev/guide/testing/components-basics',
    #'https://angular.dev/guide/testing/components-scenarios',
    #'https://angular.dev/guide/testing/attribute-directives',
    #'https://angular.dev/guide/testing/pipes',
    #'https://angular.dev/guide/testing/debugging'

    #'https://angular.dev/guide/testing/utility-apis',
    #'https://angular.dev/guide/testing/component-harnesses-overview',
    #'https://angular.dev/guide/testing/using-component-harnesses',
    #'https://angular.dev/guide/testing/creating-component-harnesses',
    #'https://angular.dev/guide/testing/component-harnesses-testing-environments',
    #'https://angular.dev/guide/i18n',
    #'https://angular.dev/guide/i18n/add-package',
    #'https://angular.dev/guide/i18n/locale-id',
    #'https://angular.dev/guide/i18n/locale-id',
    #'https://angular.dev/guide/i18n/prepare',
    
    'https://angular.dev/guide/i18n/translation-files',
    'https://angular.dev/guide/i18n/merge',
    'https://angular.dev/guide/i18n/deploy',
    'https://angular.dev/guide/i18n/import-global-variants',
    'https://angular.dev/guide/i18n/import-global-variants',
    'https://angular.dev/guide/i18n/example',
    'https://angular.dev/guide/experimental/zoneless',

    'https://angular.dev/tools/cli',
    'https://angular.dev/tools/cli',
    'https://angular.dev/tools/cli/build',
    'https://angular.dev/tools/cli/serve',
    'https://angular.dev/tools/cli/deployment',
    'https://angular.dev/tools/cli/end-to-end',
    
    "https://angular.dev/tools/cli/build-system-migration",
    
    "https://material.angular.io/components/slider/api", 
    'https://angular.dev/tools/cli/environments',
    'https://angular.dev/tools/cli/cli-builder',
    'https://angular.dev/tools/cli/schematics',
    'https://angular.dev/tools/cli/schematics-authoring',
    'https://angular.dev/tools/cli/schematics-for-libraries',
    'https://angular.dev/tools/cli/template-typecheck',
    'https://angular.dev/tools/cli/aot-compiler',
    'https://angular.dev/tools/cli/aot-metadata-errors',

    'https://angular.dev/tools/libraries',
    'https://angular.dev/tools/libraries/creating-libraries',
    'https://angular.dev/tools/libraries/using-libraries',
    'https://angular.dev/tools/libraries/angular-package-format',
    'https://angular.dev/tools/devtools',
    'https://angular.dev/tools/language-service',

    'https://angular.dev/style-guide',
    'https://angular.dev/best-practices/security',

    'https://angular.dev/best-practices/a11y',
    'https://angular.dev/best-practices/runtime-performance',
    'https://angular.dev/best-practices/zone-pollution',
    'https://angular.dev/best-practices/slow-computations',
    'https://angular.dev/best-practices/skipping-subtrees',
    'https://angular.dev/update',

    'https://angular.dev/guide/ngmodules/overview',
    'https://angular.dev/guide/animations',
    'https://angular.dev/guide/animations/transition-and-triggers',
    'https://angular.dev/guide/animations/complex-sequences',
    'https://angular.dev/guide/animations/reusable-animations',
    'https://angular.dev/guide/animations/route-animations',

    'https://angular.dev/ecosystem/rxjs-interop',
    'https://angular.dev/ecosystem/rxjs-interop/output-interop',
    'https://angular.dev/ecosystem/service-workers',
    'https://angular.dev/ecosystem/service-workers/getting-started',
    'https://angular.dev/ecosystem/service-workers/config',
    'https://angular.dev/ecosystem/service-workers/communications',
    'https://angular.dev/ecosystem/service-workers/push-notifications',
    'https://angular.dev/ecosystem/service-workers/devops',
    'https://angular.dev/ecosystem/service-workers/app-shell',
    'https://angular.dev/ecosystem/web-workers',
    'https://angular.dev/ecosystem/custom-build-pipeline'

    'https://material.angular.io/guide/getting-started',
    'https://material.angular.io/guide/schematics',
    'https://material.angular.io/guide/theming',
    'https://material.angular.io/guide/system-variables',
    'https://material.angular.io/guide/creating-a-custom-form-field-control',
    'https://material.angular.io/guide/creating-a-custom-stepper-using-the-cdk-stepper',
    'https://material.angular.io/guide/using-component-harnesses',
    'https://material.angular.io/guide/material-2-theming'

    'https://material.angular.io/components/autocomplete/overview',
    'https://material.angular.io/components/autocomplete/api',
    'https://material.angular.io/components/autocomplete/styling',
    'https://material.angular.io/components/autocomplete/examples',

    'https://material.angular.io/components/badge/overview',
    'https://material.angular.io/components/badge/api',
    'https://material.angular.io/components/badge/styling',
    'https://material.angular.io/components/badge/examples',

    'https://material.angular.io/components/bottom-sheet/overview',
    'https://material.angular.io/components/bottom-sheet/api',
    'https://material.angular.io/components/bottom-sheet/syling',
    'https://material.angular.io/components/bottom-sheet/examples',

    'https://material.angular.io/components/badge/overview',
    'https://material.angular.io/components/badge/api',
'https://material.angular.io/components/badge/styling',
'https://material.angular.io/components/badge/examples',
'https://material.angular.io/components/bottom-sheet/overview',
'https://material.angular.io/components/bottom-sheet/api',
'https://material.angular.io/components/bottom-sheet/styling',
'https://material.angular.io/components/bottom-sheet/examples',
'https://material.angular.io/components/button/overview',
'https://material.angular.io/components/button/api',
'https://material.angular.io/components/button/styling',
'https://material.angular.io/components/button/examples',
'https://material.angular.io/components/button-toggle/overview',
'https://material.angular.io/components/button-toggle/api',
'https://material.angular.io/components/button-toggle/styling',
'https://material.angular.io/components/button-toggle/examples',
'https://material.angular.io/components/button-toggle/overview',
'https://material.angular.io/components/button-toggle/api',
'https://material.angular.io/components/button-toggle/styling',
'https://material.angular.io/components/button-toggle/examples',
'https://material.angular.io/components/checkbox/overview',
'https://material.angular.io/components/checkbox/api',
'https://material.angular.io/components/checkbox/styling',
'https://material.angular.io/components/checkbox/examples',
'https://material.angular.io/components/chips/overview',
'https://material.angular.io/components/chips/api',
'https://material.angular.io/components/chips/styling',
'https://material.angular.io/components/chips/examples',
'https://material.angular.io/components/core/overview',
'https://material.angular.io/components/core/api',
'https://material.angular.io/components/core/styling',
'https://material.angular.io/components/core/examples',
'https://material.angular.io/components/datepicker/overview',
'https://material.angular.io/components/datepicker/api',
'https://material.angular.io/components/datepicker/styling',
'https://material.angular.io/components/datepicker/examples',
'https://material.angular.io/components/dialog/overview',
'https://material.angular.io/components/dialog/api',
'https://material.angular.io/components/dialog/styling',
'https://material.angular.io/components/dialog/examples',
'https://material.angular.io/components/divider/overview',
'https://material.angular.io/components/divider/api',
'https://material.angular.io/components/divider/styling',
'https://material.angular.io/components/divider/examples',
'https://material.angular.io/components/expansion/overview',
'https://material.angular.io/components/expansion/api',
'https://material.angular.io/components/expansion/styling',
'https://material.angular.io/components/expansion/examples',
'https://material.angular.io/components/form-field/overview',
'https://material.angular.io/components/form-field/api',
'https://material.angular.io/components/form-field/styling',
'https://material.angular.io/components/form-field/examples',
'https://material.angular.io/components/grid-list/overview',
'https://material.angular.io/components/grid-list/api',
'https://material.angular.io/components/grid-list/styling',
'https://material.angular.io/components/grid-list/examples',
'https://material.angular.io/components/icon/overview',
'https://material.angular.io/components/icon/api',
'https://material.angular.io/components/icon/styling',
'https://material.angular.io/components/icon/examples',
'https://material.angular.io/components/input/overview',
'https://material.angular.io/components/input/api',
'https://material.angular.io/components/input/styling',
'https://material.angular.io/components/input/examples',
'https://material.angular.io/components/list/overview',
'https://material.angular.io/components/list/api',
'https://material.angular.io/components/list/styling',
'https://material.angular.io/components/list/examples',
'https://material.angular.io/components/menu/overview',
'https://material.angular.io/components/menu/api',
'https://material.angular.io/components/menu/styling',
'https://material.angular.io/components/menu/examples',
'https://material.angular.io/components/paginator/overview',
'https://material.angular.io/components/paginator/api',
'https://material.angular.io/components/paginator/styling',
'https://material.angular.io/components/paginator/examples',
'https://material.angular.io/components/progress-bar/overview',
'https://material.angular.io/components/progress-bar/api',
'https://material.angular.io/components/progress-bar/styling',
'https://material.angular.io/components/progress-bar/examples',
'https://material.angular.io/components/progress-spinner/overview',
'https://material.angular.io/components/progress-spinner/api',
'https://material.angular.io/components/progress-spinner/styling',
'https://material.angular.io/components/progress-spinner/examples',
'https://material.angular.io/components/radio/overview',
'https://material.angular.io/components/radio/api',
'https://material.angular.io/components/radio/styling',
'https://material.angular.io/components/radio/examples',
'https://material.angular.io/components/ripple/overview',
'https://material.angular.io/components/ripple/api',
'https://material.angular.io/components/ripple/styling',
'https://material.angular.io/components/ripple/examples',
'https://material.angular.io/components/select/overview',
'https://material.angular.io/components/select/api',
'https://material.angular.io/components/select/styling',
'https://material.angular.io/components/select/examples',
'https://material.angular.io/components/sidenav/overview',
'https://material.angular.io/components/sidenav/api',
'https://material.angular.io/components/sidenav/styling',
'https://material.angular.io/components/sidenav/examples',
'https://material.angular.io/components/slide-toggle/overview',
'https://material.angular.io/components/slide-toggle/api',
'https://material.angular.io/components/slide-toggle/styling',
'https://material.angular.io/components/slide-toggle/examples',
'https://material.angular.io/components/slider/overview',
'https://material.angular.io/components/slider/styling',
'https://material.angular.io/components/slider/examples',
'https://material.angular.io/components/snack-bar/overview',
'https://material.angular.io/components/snack-bar/api',
'https://material.angular.io/components/snack-bar/styling',
'https://material.angular.io/components/snack-bar/examples',
'https://material.angular.io/components/sort/overview',
'https://material.angular.io/components/sort/api',
'https://material.angular.io/components/sort/styling',
'https://material.angular.io/components/sort/examples',
'https://material.angular.io/components/stepper/overview',
'https://material.angular.io/components/stepper/api',
'https://material.angular.io/components/stepper/styling',
'https://material.angular.io/components/stepper/examples',
'https://material.angular.io/components/table/overview',
'https://material.angular.io/components/table/api',
'https://material.angular.io/components/table/styling',
'https://material.angular.io/components/table/examples',
'https://material.angular.io/components/tabs/overview',
'https://material.angular.io/components/tabs/api',
'https://material.angular.io/components/tabs/styling',
'https://material.angular.io/components/tabs/examples',
'https://material.angular.io/components/timepicker/overview',
'https://material.angular.io/components/timepicker/api',
'https://material.angular.io/components/timepicker/styling',
'https://material.angular.io/components/timepicker/examples',
'https://material.angular.io/components/toolbar/overview',
'https://material.angular.io/components/toolbar/api',
'https://material.angular.io/components/toolbar/styling',
'https://material.angular.io/components/toolbar/examples',
'https://material.angular.io/components/tooltip/overview',
'https://material.angular.io/components/tooltip/api',
'https://material.angular.io/components/tooltip/styling',
'https://material.angular.io/components/tooltip/examples',
'https://material.angular.io/components/tree/overview',
'https://material.angular.io/components/tree/api',
'https://material.angular.io/components/tree/styling',
'https://material.angular.io/components/tree/examples',
    'https://material.angular.io/cdk/observers/overview',
    'https://material.angular.io/cdk/observers/api',

    'https://material.angular.io/cdk/a11y/overview',
    'https://material.angular.io/cdk/a11y/api',
    'https://material.angular.io/cdk/a11y/examples',
    'https://material.angular.io/cdk/accordion/overview',
    'https://material.angular.io/cdk/accordion/api',
    'https://material.angular.io/cdk/accordion/examples',
    'https://material.angular.io/cdk/bidi/overview',
    'https://material.angular.io/cdk/bidi/api',
    'https://material.angular.io/cdk/bidi/examples',
    'https://material.angular.io/cdk/clipboard/overview',
    'https://material.angular.io/cdk/clipboard/api',
    'https://material.angular.io/cdk/clipboard/examples',
    'https://material.angular.io/cdk/coercion/overview',
    'https://material.angular.io/cdk/coercion/api',
    'https://material.angular.io/cdk/coercion/examples',
    'https://material.angular.io/cdk/collections/overview',
    'https://material.angular.io/cdk/collections/api',
    'https://material.angular.io/cdk/collections/examples',
    'https://material.angular.io/cdk/testing/overview',
    'https://material.angular.io/cdk/testing/api',
    'https://material.angular.io/cdk/testing/examples',
    'https://material.angular.io/cdk/dialog/overview',
    'https://material.angular.io/cdk/dialog/api',
    'https://material.angular.io/cdk/dialog/examples',
    'https://material.angular.io/cdk/drag-drop/overview',
    'https://material.angular.io/cdk/drag-drop/api',
    'https://material.angular.io/cdk/drag-drop/examples',
    'https://material.angular.io/cdk/layout/overview',
    'https://material.angular.io/cdk/layout/api',
    'https://material.angular.io/cdk/layout/examples',
    'https://material.angular.io/cdk/listbox/overview',
    'https://material.angular.io/cdk/listbox/api',
    'https://material.angular.io/cdk/listbox/examples',
    'https://material.angular.io/cdk/menu/overview',
    'https://material.angular.io/cdk/menu/api',
    'https://material.angular.io/cdk/menu/examples',
    'https://material.angular.io/cdk/overlay/overview',
    'https://material.angular.io/cdk/overlay/api',
    'https://material.angular.io/cdk/overlay/examples',
    'https://material.angular.io/cdk/platform/overview',
    'https://material.angular.io/cdk/platform/api',
    'https://material.angular.io/cdk/platform/examples',
    'https://material.angular.io/cdk/portal/overview',
    'https://material.angular.io/cdk/portal/api',
    'https://material.angular.io/cdk/portal/examples',
    'https://material.angular.io/cdk/scrolling/overview',
    'https://material.angular.io/cdk/scrolling/api',
    'https://material.angular.io/cdk/scrolling/examples',
    'https://material.angular.io/cdk/stepper/overview',
    'https://material.angular.io/cdk/stepper/api',
    'https://material.angular.io/cdk/stepper/examples',
    'https://material.angular.io/cdk/table/overview',
    'https://material.angular.io/cdk/table/api',
    'https://material.angular.io/cdk/table/examples',
    'https://material.angular.io/cdk/text-field/overview',
    'https://material.angular.io/cdk/text-field/api',
    'https://material.angular.io/cdk/text-field/examples',
    'https://material.angular.io/cdk/tree/overview',
    'https://material.angular.io/cdk/tree/api',
    'https://material.angular.io/cdk/tree/examples'
]

import os
import json
import time
from urllib.parse import urlparse

output_dir = "raw_scraped_docs"
os.makedirs(output_dir, exist_ok=True)

for url in urls:
    try:
        # scrape with all 3 formats
        response = app.scrape_url(url=url, formats=['markdown', 'html', 'screenshot'])

        # pull out metadata fields
        meta = response.metadata
        scrape_id = meta.get("scrapeId") or getattr(response, "scrape_id", None)
        source_url = meta.get("sourceURL", url)
        status_code = meta.get("statusCode", None)

        # build result in Playground-style shape
        result = {
            "scrapeId": scrape_id,
            "sourceURL": source_url,
            "statusCode": status_code,
            "data": {
                "markdown": response.markdown,
                "screenshot": response.screenshot
            },
            "metadata": meta
        }

        # safe filename
        path = urlparse(url).path.strip('/')
        file_name = path.replace('/', '-') + '.json'

        # write out
        with open(os.path.join(output_dir, file_name), 'w', encoding='utf-8') as f:
            json.dump(result, f, ensure_ascii=False, indent=2)

        print(f"✅ Saved Playground-style JSON: {file_name}")

        # wait 20 seconds
        time.sleep(10)

    except Exception as e:
        print(f"❌ Failed to scrape {url}: {e}")
